### ISSUE TITLE
error code

### ISSUE THREAD

**Issue by dontsovcmc** [dontsovcmc/emp_mos_api#4]
отправка воды 29 числа
'errorCode'= {int} 3454
'errorMessage' = {str} 'Не удалось передать показания за март по счётчикам 123456: "Редактируемое показание принято к расчёту." '

**Comment by wouf** [comment]
Здравствуйте! На данный момент api работает? Я стабильно получаю сообщение
 `emp_mos_api.mos.EmpServerException:` Application not found `(code:403)`

**Comment by dontsovcmc** [comment]
На днях работал =). У вас он работал раньше?

**Comment by wouf** [comment]
Нет, первый раз пробовал. Может это быть из-за проблем с полями? Не совсем понял подходит ли токен от https://apidata.mos.ru и что такое guid.

**Comment by dontsovcmc** [comment]
> Нет, первый раз пробовал. Может это быть из-за проблем с полями? Не совсем понял подходит ли токен от https://apidata.mos.ru и что такое guid.

Это код общения мобильного приложения, т.е. они ждут в запросе поля про телефон, версию по и т.п.
Для https://apidata.mos.ru наверняка другие поля. Где то для HomeAssistant я видел скрипт, гляньте там что.
